[package]
name = "leroyjenkins"
version = "0.1.0"
edition = "2021"

[dependencies]
mini-moka = "0.10.2"
log = "0.4"
pretty_env_logger = "0.5"
rustc-hash = "1.1.0"
clap = { version = "4.4.2", features = ["derive"] }
ipset = {git = "https://github.com/lazytiger/ipset", rev = "30acafe"}
