[package]
name = "leroyjenkins"
version = "0.1.0"
publish = false
description = "Follow ban logs to manage ipsets"
repository = "https://github.com/lichess-org/leroyjenkins"
readme = "README.md"
license = "GPL-3.0+"
edition = "2021"

[dependencies]
mini-moka = "0.10.2"
log = "0.4"
pretty_env_logger = "0.5"
rustc-hash = "1.1.0"
clap = { version = "4.4.2", features = ["derive"] }
ipset = { git = "https://github.com/lazytiger/ipset", rev = "30acafe" }
governor = "0.6.0"
humantime = "2.1.0"
