name: Build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update && sudo apt-get install -y libipset-dev
      - uses: actions/checkout@v3
      - use: dtolnay/rust-toolchain@nightly
      - run: cargo build
